name: Deploy ChatRoom Frontstage with PM2

on:
  push:
    branches:
      - main

env:
  REMOTE_PATH: /home/AmelieKuo/project/chatroom/frontstage
  SERVER_IP: ${{ secrets.SERVER_IP }}
  SERVER_USER: ${{ secrets.SERVER_USER }}
  SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Upload source code to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ env.SERVER_IP }}
          username: ${{ env.SERVER_USER }}
          key: ${{ env.SSH_KEY }}
          source: "./*"
          target: ${{ env.REMOTE_PATH }}

      - name: SSH Build and Restart with PM2 + Backup
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ env.SERVER_IP }}
          username: ${{ env.SERVER_USER }}
          key: ${{ env.SSH_KEY }}
          script: |
            set -e
            timestamp=$(date +%Y%m%d%H%M%S)
            base_path=${{ env.REMOTE_PATH }}
            release_path=~/deploy/chatroom/releases/$timestamp

            # 備份目前版本（如果有）
            if [ -d "$base_path" ]; then
              mkdir -p ~/deploy/chatroom/releases
              cp -r $base_path $release_path
            fi

            # 保留最新三版
            ls -tp ~/deploy/chatroom/releases | grep -v '/$' | tail -n +4 | xargs -I {} rm -rf ~/deploy/chatroom/releases/{}

            # 建立最新連結
            ln -sfn $base_path ~/deploy/chatroom/current

            # 安裝與建置
            cd $base_path
            npm ci
            npm run build

            # 使用 PM2 啟動 Nuxt SSR
            pm2 delete chatroom || true
            pm2 start .output/server/index.mjs --name chatroom
